version = 0.1

[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "agrinexus-week2"
s3_prefix = "agrinexus-week2"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM"
parameter_overrides = [
    "Environment=dev",
    "TableName=agrinexus-data",
    "KnowledgeBaseId=REPLACE_WITH_YOUR_KB_ID",
    "GuardrailId=REPLACE_WITH_YOUR_GUARDRAIL_ID",
    "GuardrailVersion=1"
]

[default.build]
[default.build.parameters]
cached = true
parallel = true
